"""empty message

Revision ID: b589ebd35a58
Revises: 1dfebb54bb70
Create Date: 2023-03-23 12:52:38.901059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b589ebd35a58'
down_revision = '1dfebb54bb70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('salt', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('hashed_password', sa.String(length=500), nullable=False))
        batch_op.drop_column('password')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_column('hashed_password')
        batch_op.drop_column('salt')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
